import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/services/supabase_service.dart';
import '../../../core/constants/app_constants.dart';
import '../models/cart_model.dart';
import '../../inventory/services/inventory_service.dart';
import '../../debt/services/debt_service.dart';

/// POS service for sales transactions
class POSService {
  final SupabaseClient _supabase = SupabaseService.instance.client;
  final InventoryService _inventoryService = InventoryService();
  final DebtService _debtService = DebtService();

  /// Create a sale transaction
  Future<Sale> createSale({
    required List<CartItem> cartItems,
    String? customerId,
    required String paymentMethod,
    double discountAmount = 0,
    String? notes,
    String? createdBy,
  }) async {
    try {
      // Validate cart
      if (cartItems.isEmpty) {
        throw Exception('Giỏ hàng trống');
      }

      // Check stock availability for all items
      for (var item in cartItems) {
        final hasStock = await _inventoryService.checkStockAvailability(
          item.product.id,
          item.quantity,
        );
        if (!hasStock) {
          throw Exception(
            'Sản phẩm "${item.product.name}" không đủ hàng trong kho',
          );
        }
      }

      // If payment method is debt, check customer debt limit
      if (paymentMethod == AppConstants.paymentDebt) {
        if (customerId == null) {
          throw Exception('Phải chọn khách hàng khi bán chịu');
        }

        final totalAmount = cartItems.fold<double>(
          0,
          (sum, item) => sum + item.subtotal,
        );
        final finalAmount = totalAmount - discountAmount;

        final canBorrow = await _debtService.canCustomerBorrow(
          customerId,
          finalAmount,
        );

        if (!canBorrow) {
          throw Exception(ErrorMessages.debtLimitExceeded);
        }
      }

      // Calculate totals
      final totalAmount = cartItems.fold<double>(
        0,
        (sum, item) => sum + item.subtotal,
      );
      final finalAmount = totalAmount - discountAmount;

      // Get FEFO batches for each item
      final itemsWithBatches = <CartItem>[];
      for (var item in cartItems) {
        final batch = await _inventoryService.getFEFOBatch(
          item.product.id,
          item.quantity,
        );

        if (batch == null) {
          throw Exception('Không tìm thấy lô hàng cho "${item.product.name}"');
        }

        itemsWithBatches.add(
          item.copyWith(batchId: batch.id, costPrice: batch.costPrice),
        );
      }

      // Create sale record
      final saleData = {
        'invoice_number': '', // Will be auto-generated by trigger
        'customer_id': customerId,
        'total_amount': totalAmount,
        'discount_amount': discountAmount,
        'final_amount': finalAmount,
        'payment_method': paymentMethod,
        'payment_status': paymentMethod == AppConstants.paymentDebt
            ? AppConstants.paymentStatusUnpaid
            : AppConstants.paymentStatusPaid,
        'notes': notes,
        'created_by': createdBy,
      };

      final saleResponse = await _supabase
          .from(AppConstants.tableSales)
          .insert(saleData)
          .select()
          .single();

      final saleId = saleResponse['id'] as String;

      // Create sale items
      final saleItemsData = itemsWithBatches.map((item) {
        return {
          'sale_id': saleId,
          'product_id': item.product.id,
          'batch_id': item.batchId,
          'quantity': item.quantity,
          'unit_price': item.unitPrice,
          'cost_price': item.costPrice ?? item.product.avgCostPrice ?? 0,
          'discount': item.discount,
          'subtotal': item.subtotal,
        };
      }).toList();

      await _supabase.from(AppConstants.tableSaleItems).insert(saleItemsData);

      // Fetch complete sale with items
      final completeSale = await getSaleById(saleId);
      if (completeSale == null) {
        throw Exception('Lỗi khi tải hóa đơn vừa tạo');
      }

      return completeSale;
    } catch (e) {
      throw Exception('Lỗi khi tạo hóa đơn: ${e.toString()}');
    }
  }

  /// Get sale by ID
  Future<Sale?> getSaleById(String saleId) async {
    try {
      final saleResponse = await _supabase
          .from(AppConstants.tableSales)
          .select()
          .eq('id', saleId)
          .maybeSingle();

      if (saleResponse == null) return null;

      final itemsResponse = await _supabase
          .from(AppConstants.tableSaleItems)
          .select()
          .eq('sale_id', saleId);

      final items = (itemsResponse as List)
          .map((item) => SaleItem.fromJson(item))
          .toList();

      return Sale.fromJson({
        ...saleResponse,
        'items': items.map((e) => e.toJson()).toList(),
      });
    } catch (e) {
      throw Exception('Lỗi khi tải hóa đơn: ${e.toString()}');
    }
  }

  /// Get sales by date range
  Future<List<Sale>> getSalesByDateRange({
    required DateTime startDate,
    required DateTime endDate,
  }) async {
    try {
      final response = await _supabase
          .from(AppConstants.tableSales)
          .select()
          .gte('created_at', startDate.toIso8601String())
          .lte('created_at', endDate.toIso8601String())
          .order('created_at', ascending: false);

      return (response as List).map((item) => Sale.fromJson(item)).toList();
    } catch (e) {
      throw Exception('Lỗi khi tải danh sách hóa đơn: ${e.toString()}');
    }
  }

  /// Get today's sales
  Future<List<Sale>> getTodaySales() async {
    final now = DateTime.now();
    final startOfDay = DateTime(now.year, now.month, now.day);
    final endOfDay = startOfDay.add(const Duration(days: 1));

    return await getSalesByDateRange(startDate: startOfDay, endDate: endOfDay);
  }

  /// Generate VietQR code URL
  String generateVietQR({
    required String bankCode,
    required String accountNumber,
    required double amount,
    required String description,
  }) {
    final qrUrl =
        '${AppConstants.vietQRBaseUrl}/$bankCode-$accountNumber-${AppConstants.vietQRTemplate}.jpg'
        '?amount=${amount.toInt()}'
        '&addInfo=${Uri.encodeComponent(description)}';
    return qrUrl;
  }

  /// Calculate cart totals
  Map<String, double> calculateCartTotals(List<CartItem> items) {
    final subtotal = items.fold<double>(0, (sum, item) => sum + item.subtotal);
    final totalDiscount = items.fold<double>(
      0,
      (sum, item) => sum + item.discount,
    );
    final totalCost = items.fold<double>(
      0,
      (sum, item) => sum + (item.quantity * (item.costPrice ?? 0)),
    );
    final profit = subtotal - totalCost;

    return {
      'subtotal': subtotal,
      'totalDiscount': totalDiscount,
      'totalCost': totalCost,
      'profit': profit,
    };
  }
}
